import { icon } from './icons.js';
import { sidebar } from './Sidebar.js';

const cleanViewButton = (compact = false) => `<button type="button" class="${compact ? 'icon-button' : 'clean-view-button'}" data-action="clean-view" aria-pressed="false" aria-keyshortcuts="H" aria-label="Clean view — hide all controls (H)" title="Hide all controls (H). Escape or double-tap to restore.">${icon('eye-off')}${compact ? '' : '<span>Clean view</span><kbd>H</kbd>'}</button>`;

const iconButton = (action, symbol, label) => `<button class="icon-button" data-action="${action}" title="${label}" aria-label="${label}">${icon(symbol)}</button>`;

export function mountShell(root, bodies) {
  root.innerHTML = `${sidebar(bodies)}<main class="main-shell">
    <header class="topbar"><div class="breadcrumb"><span>UNIVERSE</span>${icon('chevron')}<strong>Solar system</strong></div><div class="mode-switch" aria-label="Simulation mode"><button class="active" data-action="explore" aria-pressed="true">${icon('orbit')}<span>Explore</span></button><button data-action="galaxy" aria-pressed="false">${icon('galaxy')}<span>Galaxy</span></button><button data-action="flight" aria-pressed="false">${icon('ship')}<span>Flight deck</span></button></div><div class="topbar-tools"><span class="live-label"><span class="online-dot"></span>LIVE SIMULATION</span>${cleanViewButton()}${iconButton('help', 'help', 'Controls and help (?)')}${iconButton('settings', 'settings', 'Simulation settings')}${iconButton('fullscreen', 'expand', 'Full screen view')}</div></header>
    <section class="viewport" aria-label="Solar system simulator"><div id="scene"></div><div class="scene-vignette"></div><div id="body-labels" class="body-labels"></div>
      <div class="scene-heading"><div class="eyebrow">A UNIVERSE TO EXPLORE</div><div class="scene-location">The pale blue dot<span>EARTH · SOL SYSTEM</span></div></div>
      <div class="galaxy-perspectives" role="group" aria-label="Galaxy perspective"><button data-galaxy-view="structure" class="active" aria-pressed="true">3D galaxy</button><button data-galaxy-view="edge" aria-pressed="false">Edge-on</button><button data-galaxy-view="sky" aria-pressed="false">From Earth</button></div>
      <div class="sky-credit">Observed sky · <a href="https://www.eso.org/public/images/eso0932a/" target="_blank" rel="noopener">ESO/S. Brunier</a></div>
      <div class="coordinate-mark top-left"></div><div class="coordinate-mark bottom-left"></div>
      <aside id="object-panel" class="object-panel" aria-label="Selected celestial body"></aside>
      <div class="view-indicator"><span class="tiny-cross">+</span><span id="view-label">ORBITAL VIEW</span><span class="view-line"></span><span id="view-detail">EARTH</span></div>
      <div class="canvas-tools">${iconButton('orbits', 'orbit', 'Toggle orbital paths')}${iconButton('labels', 'layers', 'Toggle planet labels')}${iconButton('lock-orbit', 'target', 'Lock orbit camera (L)')}<span class="tool-divider"></span>${iconButton('zoom-in', 'plus', 'Zoom in')}${iconButton('zoom-out', 'minus', 'Zoom out')}${iconButton('recenter', 'target', 'Recenter view (R)')}<span class="tool-divider"></span>${cleanViewButton(true)}${iconButton('snapshot', 'camera', 'Save a space photograph')}${iconButton('fullscreen', 'expand', 'Toggle fullscreen')}</div>
      <div class="orbit-hint">${icon('compass')}<span><b>Drag</b> to orbit <i>·</i> <b>Scroll</b> to zoom</span></div>
      <div class="flight-hud" id="flight-hud"><div class="flight-heading"><span class="online-dot"></span><span id="flight-state">MANUAL FLIGHT</span></div><div class="flight-reticle"><span></span><i></i></div><div class="flight-telemetry"><div><span class="eyebrow">VELOCITY</span><strong id="flight-speed">0.0 <small>u/s</small></strong><div class="velocity-track"><span id="velocity-fill"></span></div></div><div><span class="eyebrow">TARGET RANGE</span><strong id="flight-distance">—</strong><span id="flight-target">Free flight</span></div></div><div class="flight-actions"><button data-action="pointer-lock">${icon('target')} Mouse steering</button><button data-action="view">${icon('eye')}<span id="flight-view">Cockpit view</span></button><button data-action="brake">Brake <kbd>Space</kbd></button>${cleanViewButton(true)}${iconButton('reset-flight', 'reset', 'Reset spacecraft near target')}</div><div class="flight-guide"><span><kbd>W</kbd><kbd>S</kbd> Thrust</span><span><kbd>↑</kbd><kbd>↓</kbd><kbd>A</kbd><kbd>D</kbd> Steer</span><span><kbd>Q</kbd><kbd>E</kbd> Roll</span><span><kbd>Shift</kbd> Boost</span><span><kbd>Esc</kbd> Release mouse</span></div><div class="flight-touch-layer" id="flight-touch-layer" aria-hidden="true"><div class="virtual-joystick" id="virtual-joystick"><div class="virtual-joystick-ring"></div><div class="virtual-joystick-knob"></div></div><div class="touch-thrust-zone" data-touch-thrust><span>THRUST</span><small>hold · two fingers to boost</small></div><div class="touch-flight-hint">Touch and drag to steer · hold the right side to thrust</div></div></div>
      <div id="clean-view-hint" class="clean-view-hint" role="status" aria-live="polite" hidden></div>
    </section>
    <footer class="timeline"><div class="time-controls"><button class="pause-button" data-action="pause" aria-label="Pause simulation">${icon('pause')}</button><div><div class="eyebrow">SIMULATION TIME</div><div class="date-line"><time id="simulation-date">JAN 01, 2026</time><span id="time-state">RUNNING</span></div></div></div><div class="time-speed"><span class="eyebrow">TIME WARP</span><select id="time-speed" aria-label="Simulation speed"><option value="0.1">0.1 day / sec</option><option value="1">1 day / sec</option><option value="10">10 days / sec</option><option value="30">30 days / sec</option><option value="100">100 days / sec</option></select><button class="icon-button" data-action="reset-time" title="Reset simulation date" aria-label="Reset simulation date">${icon('reset')}</button></div><div class="timeline-note"><span class="scale-dot"></span>True periods. Reimagined scale.<button data-action="about" aria-label="About simulation scale">${icon('help')}</button></div></footer>
  </main><div id="rotate-device" class="rotate-device-overlay" role="status" aria-live="polite"><div class="rotate-device-art" aria-hidden="true"><div class="rotate-arrow rotate-arrow-left">↶</div><div class="rotate-phone"><span>ROTATE<br>YOUR<br>DEVICE</span><i></i></div><div class="rotate-arrow rotate-arrow-right">↷</div></div><strong>Rotate your device</strong><p>Turn your phone sideways for the full flight deck</p></div><div id="toast" class="toast" role="status" aria-live="polite"></div><dialog id="modal" aria-labelledby="modal-title"><div id="modal-content"></div></dialog>`;
}

export function modalContent(type, settings) {
  const close = `<button class="icon-button modal-close" data-action="close-modal" aria-label="Close dialog">${icon('close')}</button>`;
  if (type === 'settings') return `${close}<span class="eyebrow">MAKE SPACE YOUR OWN</span><h2 id="modal-title">Your observatory.</h2><p class="modal-intro">A few small adjustments to your view of the universe.</p><label class="setting-row"><span><strong>Orbital paths</strong><small>Trace each planet’s journey around the Sun</small></span><input type="checkbox" data-setting="orbits" ${settings.orbits ? 'checked' : ''}></label><label class="setting-row"><span><strong>Object labels</strong><small>Find your bearings in the solar system</small></span><input type="checkbox" data-setting="labels" ${settings.labels ? 'checked' : ''}></label><label class="setting-row"><span><strong>Graphics quality</strong><small>Balanced uses less power on smaller devices</small></span><select data-setting="quality"><option value="high" ${settings.quality === 'high' ? 'selected' : ''}>High</option><option value="balanced" ${settings.quality === 'balanced' ? 'selected' : ''}>Balanced</option></select></label><button class="secondary-button" data-action="clean-view" aria-pressed="false">${icon('eye-off')} Clean view <kbd>H</kbd></button><p class="help-tip">Hide the entire interface. Press <kbd>H</kbd> or <kbd>Esc</kbd>, or double-tap the scene, to bring it back.</p>`;
  if (type === 'journeys') return `${close}<span class="eyebrow">FOLLOW YOUR CURIOSITY</span><h2 id="modal-title">The next frontier.</h2><p class="modal-intro">Pick a destination. Your flight computer handles the approach; take control whenever you like.</p><div class="journey-options"><button data-journey="saturn"><span class="journey-index">01</span><span><strong>Among the rings</strong><small>Approach Saturn’s great rings of ice and rock.</small></span>${icon('arrow')}</button><button data-journey="mars"><span class="journey-index">02</span><span><strong>A world of rust</strong><small>Set a course for our red planetary neighbor.</small></span>${icon('arrow')}</button><button data-journey="neptune"><span class="journey-index">03</span><span><strong>Into the deep blue</strong><small>Travel to the edge of the planetary system.</small></span>${icon('arrow')}</button></div>`;
  if (type === 'about') return `${close}<span class="eyebrow">THE SCIENCE OF EXPLORATION</span><h2 id="modal-title">Space, with perspective.</h2><p class="modal-intro">Cosmic Fusion is an interactive educational model of our solar system.</p><div class="about-copy"><p><strong>Real orbital periods, illustrative positions.</strong> Planets follow circular paths using their relative orbital periods. The calendar advances the simulation; positions are not astronomical predictions.</p><p><strong>A universe you can navigate.</strong> Planet sizes and distances are compressed independently. Flight uses simulation units (u), with assisted steering and braking rather than gravitational flight dynamics. Entering flight holds the orbital clock so destinations stay approachable.</p><p><strong>A closer look.</strong> Planets use local imagery-based maps from <a href="https://www.solarsystemscope.com/textures/" target="_blank" rel="noopener">Solar System Scope</a> (CC BY 4.0; NASA-based data), with color and lighting adjustments. Unmapped areas include reconstruction. The 3D Milky Way is a statistical model with 260,000 star particles, not a measured star catalogue. The view from Earth uses a photographic panorama by <a href="https://www.eso.org/public/images/eso0932a/" target="_blank" rel="noopener">ESO/S. Brunier</a> (CC BY 4.0). Planet facts are approximate educational values.</p></div>`;
  return `${close}<span class="eyebrow">MISSION BRIEFING</span><h2 id="modal-title">Find your way.</h2><div class="help-section"><h3>Explore</h3><div><span>Orbit a world</span><kbd>Drag</kbd></div><div><span>Zoom in / out</span><kbd>Scroll / pinch</kbd></div><div><span>Pan the view</span><kbd>Right drag</kbd></div><div><span>Solar system / recenter</span><span><kbd>1</kbd> / <kbd>R</kbd></span></div><div><span>Pause time</span><kbd>Space</kbd></div><div><span>Hide / show interface</span><kbd>H</kbd></div><div><span>Leave clean view</span><span><kbd>Esc</kbd> / double-click or double-tap</span></div></div><div class="help-section"><h3>Flight deck</h3><div><span>Forward / reverse thrust</span><span><kbd>W</kbd> <kbd>S</kbd></span></div><div><span>Pitch / yaw</span><span><kbd>↑</kbd> <kbd>↓</kbd> <kbd>A</kbd> <kbd>D</kbd></span></div><div><span>Roll / boost / brake</span><span><kbd>Q E</kbd> <kbd>Shift</kbd> <kbd>Space</kbd></span></div></div><p class="help-tip">Choose <strong>Fly to</strong> for an assisted approach. Thrust or steering returns you to manual control. Mouse steering is optional; <kbd>Esc</kbd> releases the cursor. Switch back to <strong>Explore</strong> to leave the spacecraft.</p>`;
}
